// <auto-generated />
namespace Employees.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Authorization1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Authorization1));
        
        string IMigrationMetadata.Id
        {
            get { return "202001271142025_Authorization1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
